version: '3'
services:
  app:
    image: dyoshikawa/rails-api
    volumes:
      - .:/myproject:cached
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/postgresql/data:cached
    ports:
      - 5432:5432
