version: '3'
services:
  app:
    image: dyoshikawa/rails-api:latest
    volumes:
      - .:/myproject:cached
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: dyoshikawa/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: development
    volumes:
      - ./mysql-data:/var/lib/mysql:cached
    ports:
      - 3306:3306
